void *malloc_checked(unsigned int b);
char *string_nconcat(char *s1, char *s2, unsigned int n);
void *_calloc(size_t, size_t);
int *array_range(int min, int max);
void *_realloc(void *ptr, size_t old_size, size_t new_size);
void _print(char *str, int l);
char *mul(char n, char *num, int num_index, char *dest, int dest_index);
int check_for_digits(char **av);
void init(char *str, int l);
int _putchar(char c);
